AWSTemplateFormatVersion: "2010-09-09"
Description: Simple EC2 Instance using CloudFormation with proper comments

Resources:
  # -----------------------------------
  # Security Group
  # Allows SSH access from anywhere
  # -----------------------------------
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Allows SSH from anywhere (not recommended for production)

  # -----------------------------------
  # EC2 Instance
  # -----------------------------------
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro # Free tier eligible
      KeyName: temp # Replace with your key pair name

      # -----------------------------------
      # OPTION 1 (Hardcoded AMI - Basic Learning Method)
      # Region: us-east-1
      # -----------------------------------
      ImageId: ami-0c1fe732b5494dc14

      # -----------------------------------
      # OPTION 2 (Recommended - Dynamic Latest AMI)
      # Uses SSM Parameter Store
      # Automatically fetches latest Amazon Linux 2023 AMI
      # Uncomment below and comment ImageId above
      # -----------------------------------
      # ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'

      SecurityGroupIds:
        - !Ref MySecurityGroup # References Security Group created above

Outputs:
  # -----------------------------------
  # Output Public IP of EC2
  # -----------------------------------
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
